<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-E36DAG2Q" ignored="0" name="Default test" tests="2" failures="0" timestamp="11 Aug 2018 12:05:00 GMT" time="0.082" errors="0">
  <testcase name="@BeforeClass initialize" time="0.001" classname="com.prevail.utilgeneric.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.prevail.utilgeneric.BaseTest.initialize(BaseTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass initialize -->
  <testcase name="@BeforeMethod extReport" time="0.0" classname="com.prevail.utilgeneric.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod extReport -->
  <testcase name="@AfterMethod endTest" time="0.0" classname="com.prevail.utilgeneric.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod endTest -->
  <testcase name="@BeforeMethod extReport" time="0.0" classname="com.prevail.utilgeneric.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod extReport -->
  <testcase name="@AfterMethod endTest" time="0.0" classname="com.prevail.utilgeneric.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod endTest -->
  <testcase name="@AfterTest endTest" time="0.0" classname="com.prevail.utilgeneric.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterTest endTest -->
  <testcase name="TC01_logIn_UI_" time="0.0" classname="com.prevail.profile.Login">
    <skipped/>
  </testcase> <!-- TC01_logIn_UI_ -->
  <testcase name="TC02_logIn_ForgotPassword" time="0.0" classname="com.prevail.profile.Login">
    <skipped/>
  </testcase> <!-- TC02_logIn_ForgotPassword -->
</testsuite> <!-- Default test -->
